# Generated by Django 3.2.18 on 2023-06-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='feed',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
    ]
