# Generated by Django 3.2.18 on 2023-06-07 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_category'),
        ('content', '0007_remove_feed_image'),
    ]

    operations = [
    ]
