# Generated by Django 3.2.18 on 2023-06-10 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='receive_user',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='send_user',
        ),
    ]
