# Generated by Django 3.2.18 on 2023-06-21 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0016_auto_20230621_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='receive_user',
            field=models.ForeignKey(db_column='receive_user', on_delete=django.db.models.deletion.CASCADE, related_name='received_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alert',
            name='send_user',
            field=models.ForeignKey(db_column='send_user', on_delete=django.db.models.deletion.CASCADE, related_name='sent_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='receive_user',
            field=models.ForeignKey(db_column='receive_user', on_delete=django.db.models.deletion.CASCADE, related_name='received_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='send_user',
            field=models.ForeignKey(db_column='send_user', on_delete=django.db.models.deletion.CASCADE, related_name='sent_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(db_column='follower', on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(db_column='following', on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
