# Generated by Django 3.2.18 on 2023-05-17 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_name_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
    ]
