# Generated by Django 3.2.18 on 2023-05-11 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_feed_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='is_marked',
        ),
        migrations.RemoveField(
            model_name='like',
            name='is_like',
        ),
    ]
