# Generated by Django 3.2.18 on 2023-05-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20230511_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.EmailField(default='', max_length=254)),
                ('following', models.EmailField(default='', max_length=254)),
            ],
        ),
    ]
