# Generated by Django 3.2.18 on 2023-06-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20230608_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_user', models.EmailField(default='', max_length=254)),
                ('receive_user', models.EmailField(default='', max_length=254)),
                ('chat_content', models.TextField()),
            ],
        ),
    ]
