# Generated by Django 3.2.18 on 2023-06-10 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20230608_0231'),
        ('content', '0008_merge_0006_category_0007_remove_feed_image'),
    ]

    operations = [
    ]
