# Generated by Django 3.2.18 on 2023-06-11 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20230610_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='receive_user',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='chat',
            name='send_user',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
