# Generated by Django 3.2.18 on 2023-06-13 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_chat_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='create_at',
            new_name='send_time',
        ),
    ]
