# Generated by Django 3.2.18 on 2023-06-14 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_merge_20230610_0954'),
        ('content', '0012_rename_create_at_chat_send_time'),
    ]

    operations = [
    ]
