# Generated by Django 3.2.18 on 2023-06-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_rename_create_at_chat_send_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_user', models.EmailField(default='', max_length=254)),
                ('receive_user', models.EmailField(default='', max_length=254)),
                ('chat_content', models.TextField()),
                ('send_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
