# Generated by Django 3.2.18 on 2023-06-14 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_alert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='chat_content',
            new_name='alert_content',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='receive_user',
            new_name='alert_receive_user',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='send_user',
            new_name='alert_send_user',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='send_time',
            new_name='alert_time',
        ),
    ]
