# Generated by Django 3.2.18 on 2023-06-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20230614_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='feed_id',
            field=models.IntegerField(default=0),
        ),
    ]
