# Generated by Django 3.2.18 on 2023-06-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_alert_feed_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='reply_content',
            field=models.TextField(default=''),
        ),
    ]
