# Generated by Django 3.2.18 on 2023-06-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_auto_20230621_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='receive_user',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='alert',
            name='send_user',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='chat',
            name='receive_user',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='chat',
            name='send_user',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='feed',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='like',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='reply',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='sharecategory',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
